<?php
$bgImages = Array (
	Array('hills', 'trees'),
	Array('plains', 'pine'),
	Array('eciel', 'enuages'),
	Array('desert', 'roc'),
	Array('ciel', 'nuages'),
	Array('nuit', 'boos'),
	Array('volcans', 'pilliers'),
	Array('space', 'etoiles'),

	Array('clouds','castle','bush'),
	Array('palms','boat','waves'),
	Array('sunset','grass','baobabs'),
	Array('darkness','bowser','pillars'),
	Array('fhills','shills','oaks'),
	Array('spectrum','mansion','dtrees'),
	Array('earth','dunes','sandcastle'),
	Array('shield','throne','ark'),
	Array('factory','airship','rain'),
	Array('bean','yairship','yclouds'),
	Array('sun','sand','lighthouse'),
	Array('sunrise','canyon','valley'),
	Array('pclouds','cristals','diamonds'),
	Array('sclouds','garland','gifts'),
	Array('dclouds','pyramids','mound'),
	Array('storm','dongeons','towers'),
	Array('scree','volcanos','willows'),
	Array('cave','hallow','stalagmites'),
	Array('hose','duct','grilling'),
	Array('night','ship','nclouds'),

	Array('mariosky','hills8','banners8'),
	Array('yoshisky','cliff','cascade'),
	Array('lightsky','coconut'),
	Array('lugubrousky','moon','luigimansion'),
	Array('desertsky','movingsun','sandhills','sandtower'),
	Array('yoshisky','town'),
	Array('sparkles','pinball'),
	Array('mariosky','treehills','ridge'),
	Array('alpsky','alpmounts','alppeak','alpfir'),
	Array('clocks','gear'),
	Array('mariosky','mariohills','mariobush','mariobanners'),
	Array('airsky','ship3','ship2','ship1','arrowslit'),
	Array('wariosky','tribune','wariobanner'),
	Array('mariosky','treehills','fence','flowers','garden'),
	Array('bowsersky','mounts','moat','tower'),
	Array('nightsky','shootingstars'),

	Array('ds'),
	Array('twilightsky','twilighthouse'),
	Array('piesky','pie'),
	Array('palmsky')
);