name: PHP lint
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
jobs:
  php_lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl
      - name: Check for syntax errors
        run: make php-lint
      - name: Check translations
        run: make translations-lint
